version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker/development/nginx
    ports:
      - "${GATEWAY}:8080"
    depends_on:
      - app

  app:
    build:
      context: app/docker/development/nginx
    volumes:
      - ./app:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: app/docker/development/php-fpm
    volumes:
      - ./app:/app